# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: e-editiones
email: roberta.padlina@gmail.com # hanscoolssw@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Machine interpretable and interoperable semantics for Humanities

baseurl: "/" # the subpath of your site, e.g. /blog

# url: "http://e-editiones.ch" # the base hostname & protocol for your site, e.g. http://example.com

github_username:  nie-ine
github_repo: e-editiones
github_ontologies: https://github.com/nie-ine/Ontologies/blob/master/Nie-ontologies

# Build settings
# theme: minima
#plugins:

# Ontology collections
collections_dir: collections
collections: 
  generalDomain:
    output: true
    # permalink: /ontology/:name
  generalHumanities:
    output: true
    # permalink: /ontology/:name
  specificHumanities:
    output: true
    # permalink: /ontology/:name
  external:
    output: true
    # permalink: /ontology/:name
  project: 
    output: true
    # permalink: /ontology/:name

defaults: 
  - scope:
      path: ""
      type: "generalDomain"
    values:
      layout: "ontology"
  - scope:
      path: ""
      type: "generalHumanities"
    values:
      layout: "ontology"
  - scope:
      path: ""
      type: "specificHumanities"
    values:
      layout: "ontology"
  - scope:
      path: ""
      type: "external"
    values:
      layout: "ontology"
  - scope:
      path: ""
      type: "project"
    values:
      layout: "ontology"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
exclude: [ttl_conv]
