# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: e-editiones
email: roberta.padlina@gmail.com # hanscoolssw@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Machine interpretable and interoperable semantics for Humanities

url: "https://e-editiones.ch" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/" # the subpath of your site, e.g. /blog

# url: "https://nie-ine.github.io"
# baseurl: "/e-editiones"

github_username:  nie-ine
github_repo: e-editiones
github_ontologies: https://github.com/nie-ine/Ontologies/blob/master/Nie-ontologies

# Build settings
destination: docs/
exclude: [ttl_conv, docs, README.md]

# Ontology collections
collections_dir: collections
collections: 
  generalDomain:
    output: true
    permalink: ontology/:name
  generalHumanities:
    output: true
    permalink: ontology/:name
  specificHumanities:
    output: true
    permalink: ontology/:name
  external:
    output: true
    permalink: ontology/:name
  project: 
    output: true
    permalink: ontology/:name

defaults: 
  - scope:
      path: ""
      type: "generalDomain"
    values:
      layout: "ontology"
  - scope:
      path: ""
      type: "generalHumanities"
    values:
      layout: "ontology"
  - scope:
      path: ""
      type: "specificHumanities"
    values:
      layout: "ontology"
  - scope:
      path: ""
      type: "external"
    values:
      layout: "ontology"
  - scope:
      path: ""
      type: "project"
    values:
      layout: "ontology"
